routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('test', function() {
  return view('testviews.test');
});

Route::get('perfil', 'profileController@show')->name('perfil.show');
Route::get('perfil/crear', 'profileController@create')->name('perfil.create');
Route::post('perfil', 'profileController@store')->name('perfil.store');
Route::post('perfil/unificar', 'profileController@unificar')->name('perfil.unificar');
Route::get('perfil/editar', 'profileController@edit')->name('perfil.edit');
Route::put('perfil/', 'profileController@update')->name('perfil.update');
Route::get('perfil/json', 'profileController@json')->name('perfil.json');
Route::get('perfil/search', 'profileController@search')->name('perfil.search');
Route::get('perfil/asociar', 'profileController@mostrar')->name('profile.buscar');
Route::get('perfil/asociar/{id}', 'profileController@asociar');

Route::get('dashboard', 'mainController@dashboard')->name('dashboard');

Route::resource('proyecto', 'proyectoController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Proyecto.php
<?php

namespace gestionInnovacion;

use Illuminate\Database\Eloquent\Model;

class Proyecto extends Model
{
  protected $table = 'proyectos';

  protected $fillable = [
    'titulo'
  ];

  public function __toString()
  {
    return $this->titulo;
  }

  /**
   * Get the protocolo record associated with the proyecto.
   */
  public function protocolo()
  {
    return $this->hasOne('GDriveConnector\Protocolo')->withDefault();
  }

  public function participantes()
  {
    return $this->belongsToMany('GDriveConnector\Profile')->withTimestamps();
  }

  /**
   * Get the contact record associated with the proyecto.
   */
  public function contacto()
  {
    return $this->belongsTo('GDriveConnector\Profile', 'contacto_id')->withDefault();
  }
}

app/Http/Controllers/proyectoController.php
<?php

namespace gestionInnovacion\Http\Controllers;

use Illuminate\Http\Request;
use gestionInnovacion\Proyecto;

class proyectoController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    //
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    //
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param \Illuminate\Http\Request $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    //
  }

  /**
   * Display the specified resource.
   *
   * @param int $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
    //
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param int $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
    $proyecto = Proyecto::find($id);
    return view('proyecto.form', [
      'proyecto'  => $proyecto
    ]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param \Illuminate\Http\Request $request
   * @param int $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
    dd($request->all());
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param int $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
    //
  }
}

resources/views/proyecto/form.blade.php
@extends("layouts.main")

@section('content')
  <div class="portlet box blue">
    <div class="portlet-title">
      <div class="caption">
        <i class="fa fa-gift"></i>{{ $proyecto}} </div>
    </div>
    <div class="portlet-body form">
      <!-- BEGIN FORM-->
      <form class="horizontal-form" role="form" action="{{ route('proyecto.update', $proyecto) }}" method="POST">
        {{ method_field('PUT') }}

        {{ csrf_field() }}
        <div class="form-body">
          <h4 class="form-section">Datos Generales</h4>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label class="control-label">Titulo:</label>
                <input type="text" name="titulo" value="{{ old('titulo', $proyecto->titulo) }}" class="form-control">
              </div>
            </div>
            <!--/span-->
          </div>
          <!--/row-->

          <h4 class="form-section">Investigador Principal</h4>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label class="control-label"> Investigador Principal:</label>
                <input type="text" name="inv_princ" value="{{ old('inv_princ', $proyecto->inv_princ) }}" class="form-control">
              </div>
            </div>
            <!--/span-->
            <div class="col-md-6">
              <div class="form-group">
                <label class="control-label">Departamento/Servicio/Unidad/Área/Centro:</label>
                <input type="text" name="inv_princ_area" value="{{ old('inv_princ_area', $proyecto->inv_princ_area) }}" class="form-control">
              </div>
            </div>
            <!--/span-->
          </div>
          <!--/row-->

          <h4 class="form-section">Persona de Contacto</h4>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label class="control-label">Nombre:</label>
                <input type="text" name="titulo" value="{{ old('titulo', $proyecto->titulo) }}" class="form-control">
              </div>
            </div>
            <!--/span-->
            <div class="col-md-6">
              <div class="form-group">
                <label class="control-label">Correo Electronico:</label>
                <input type="text" name="email" value="{{ old('email', $proyecto->email) }}" class="form-control">
              </div>
            </div>
            <!--/span-->
          </div>
          <!--/row-->

          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label class="control-label">Tel. Oficina:</label>
                <input type="text" name="tel_oficina" value="{{ old('tel_oficina', $proyecto->tel_oficina) }}" class="form-control">
              </div>
            </div>
            <!--/span-->
            <div class="col-md-6">
              <div class="form-group">
                <label class="control-label">Tel. Movil:</label>
                <input type="text" name="telefono" value="{{ old('telefono', $proyecto->telefono) }}" class="form-control">
              </div>
            </div>
            <!--/span-->
          </div>
          <!--/row-->
        </div>

        <div class="form-actions">
          <div class="row">
            <div class="col-md-12">
              <div class="row">
                <div class="col-md-offset-5 col-md-7">
                  <a href="{{ route('dashboard') }}" class="btn default"><i class="fa fa-remove"></i> Cancelar</a>
                  <button type="submit" class="btn green-jungle"><i class="fa fa-save"></i> Guardar Cambios</button>
                </div>
              </div>
            </div>
            <div class="col-md-6"> </div>
          </div>
        </div>
      </form>
      <!-- END FORM-->
    </div>
  </div>
@endsection