routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('test', function() {
  return view('testviews.test');
});

Route::get('perfil', 'profileController@show')->name('perfil.show');
Route::get('perfil/crear', 'profileController@create')->name('perfil.create');
Route::post('perfil', 'profileController@store')->name('perfil.store');
Route::post('perfil/unificar', 'profileController@unificar')->name('perfil.unificar');
Route::get('perfil/editar', 'profileController@edit')->name('perfil.edit');
Route::put('perfil/', 'profileController@update')->name('perfil.update');
Route::get('perfil/json', 'profileController@json')->name('perfil.json');
Route::get('perfil/search', 'profileController@search')->name('perfil.search');
Route::get('perfil/asociar', 'profileController@mostrar')->name('profile.buscar');
Route::get('perfil/asociar/{id}', 'profileController@asociar');

Route::get('dashboard', 'mainController@dashboard')->name('dashboard');

Route::resource('proyecto', 'proyectoController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/mainController.php
<?php

namespace gestionInnovacion\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class mainController extends Controller
{
  public function dashboard()
  {
    $user = Auth::user();
    $profile = $user->profile;
    $proyectos = $profile->proyectos;
    return view('main.dashboard', [
      'user'      =>  $user,
      'profile'   =>  $profile,
      'proyectos' =>  $proyectos
    ]);
  }
}

resources/views/main/dashboard.blade.php
@extends("layouts.main")

@section('content')
<div class="row">
  <div class="col-md-10">
    <div class="portlet box yellow">
      <div class="portlet-title">
        <div class="caption">
          <i class="fa fa-cogs"></i>Mis Proyectos </div>
      </div>
      <div class="portlet-body">
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover">
            <thead>
              <tr>
                <th> # </th>
                <th> Nombre </th>
                <th nowrap> Investigador Principal </th>
                <th nowrap> Avance Reportado </th>
                <th nowrap> Acciones </th>
              </tr>
            </thead>
            <tbody>
@foreach($proyectos as $item)
              <tr>
                <td> {{ $loop->iteration }} </td>
                <td><a href="{{ route('proyecto.edit', $item) }}">{{ $item->titulo }} </a></td>
                <td> {{ $item->inv_princ }} </td>
                <td nowrap> {{ $item->avance }} </td>
                <td nowrap> Table cell </td>
              </tr>
@endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection